//    Copyright 2006-2010 Krisztian Magori, Mathieu Legros, Alun Lloyd, Fred Gould
//
//    This file is part of Skeeter Buster.
//
//    Skeeter Buster is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Skeeter Buster is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Skeeter Buster.  If not, see <http://www.gnu.org/licenses/>.

#include "stdafx.h"
#include "Aedes_class_defs.h"
#include "Aedes.h"
//#include "stdafx.h"

bool SIMULATION_MODE1=1;
bool SIMULATION_MODE2=1;
bool REPRODUCTION_MODE=0;
bool DEVELOPMENT_MODE=0;

bool NOPUPATION=0;
bool MARK_RELEASE_RECAPTURE=0;

bool DATED_OUTPUT=1;
bool LOG_PER_HOUSE=0;
bool OUTPUT_PER_CONTAINER_TYPE=0;
bool OUTPUT_PER_CONTAINER=0;
bool OUTPUT_WATER_LEVEL=0;
int OUTPUT_PER_CONTAINER_START_DATE=0;
bool DETAILED_LOG=0;
int DETAILED_LOG_START=0;
int DETAILED_LOG_END=0;
bool EPS_OUTPUT=0;
int EPS_OUTPUT_FREQ=0;
bool EPS_WOLBACHIA_OUTPUT=0;
int EPS_WOLBACHIA_OUTPUT_FREQ=0;
bool EPS_DENSITY_OUTPUT=0;
int EPS_DENSITY_OUTPUT_FREQ=0;
bool EPS_XT_OUTPUT=0;
bool EPS_YT_OUTPUT=0;
bool OUTPUT_FOR_SBEED=0;
bool SPATIAL_STATS=1;
bool FSTATS=0;
bool TEST_1=false;
bool TEST_2=false;
bool GENTIME=false;
bool LARVTIME=false;
bool SAVE_FINAL_STATE_AS_SETUP_FILE=false;
bool ZIPPED_OUTPUT=false;

bool DONT_POPUP=1;
bool HTML_OUTPUT=1;

bool DESTINATION=0;
string RESULTS_DIR="";
string GNUPLOT_DIR="";

int NUMBER_OF_DAYS=365;

int CHROM_NUMBER=3;

int GENETIC_CONTROL_METHOD=0;

int TRADITIONAL_CONTROL_METHOD=0;

int ADULTICIDE_BEGIN_DATE=365;
int ADULTICIDE_END_DATE=365;
int ADULTICIDE_FREQUENCY=1;
int ADULTICIDE_TYPE=0;
int ADULTICIDE_RESIDUAL_LENGTH=0;
int ADULTICIDE_REGION=0;
int ADULTICIDE_SIZE=10;
int ADULTICIDE_REGION_2_XMIN=0;
int ADULTICIDE_REGION_2_XMAX=0;
int ADULTICIDE_REGION_2_YMIN=0;
int ADULTICIDE_REGION_2_YMAX=0;
double ADULTICIDE_EFFICACY=0.9;
double ADULTICIDE_EFFICACY_DECREASE=0.5;
double ADULTICIDE_COMPLIANCE=0.9;

int LARVICIDE_BEGIN_DATE=365;
int LARVICIDE_END_DATE=365;
int LARVICIDE_FREQUENCY=1;
int LARVICIDE_TYPE=0;
int LARVICIDE_REGION=0;
int LARVICIDE_SIZE=10;
int LARVICIDE_REGION_2_XMIN=0;
int LARVICIDE_REGION_2_XMAX=0;
int LARVICIDE_REGION_2_YMIN=0;
int LARVICIDE_REGION_2_YMAX=0;
double LARVICIDE_CONTAINER_PROBABILITY=0.8;
double LARVICIDE_EFFICACY_ON_EGGS=0.95;
double LARVICIDE_EFFICACY_ON_LARVAE=0.95;
double LARVICIDE_EFFICACY_ON_PUPAE=0.95;
double LARVICIDE_COMPLIANCE=0.9;

int SOURCE_REMOVAL_BEGIN_DATE=365;
int SOURCE_REMOVAL_TYPE=0;
int SOURCE_REMOVAL_REGION=0;
int SOURCE_REMOVAL_SIZE=10;
int SOURCE_REMOVAL_REGION_2_XMIN=0;
int SOURCE_REMOVAL_REGION_2_XMAX=0;
int SOURCE_REMOVAL_REGION_2_YMIN=0;
int SOURCE_REMOVAL_REGION_2_YMAX=0;
double SOURCE_REMOVAL_PROPORTION=1.0;
double SOURCE_REMOVAL_COMPLIANCE=0.9;


int CONDUCT_DESTRUCTIVE_SAMPLING = 0;
int NUMBER_OF_DAYS_SAMPLED = 0;
int DESTRUCTIVE_LARVAE_SAMPLING = 0;
int DESTRUCTIVE_ADULT_SAMPLING = 0;
int DESTRUCTIVE_PUPAE_SAMPLING = 0;

double SAMPLE_CONTAINER_PROBABILITY = 1;
double PROPORTION_OF_EGGS_SAMPLED = 1;
double PROPORTION_OF_LARVAE_SAMPLED = 1;
double PROPORTION_OF_ADULT_FEMALES_SAMPLED = 1;
double PROPORTION_OF_ADULT_MALES_SAMPLED = 1;
double PROPORTION_OF_PUPAE_SAMPLED = 1;


int DISPERSAL_MODE=0;

int FOOD_INPUT_METHOD=0;

int CONTAINER_MULTIPLIER_FACTOR=1;

int INCREASED_CONTAINER_VARIANCE=0;
int INCREASED_VARIANCE_EVERY_N_HOUSES=4;

int FITNESS_COST_STAGE=0;
int FITNESS_COST_STAGE_RR = 0;
int TETRACYCLINE = 0;
int FITNESS_COST_STAGE_SPECIFIC_AGE=0;
int EMBRYONIC_COST_SELECTION_TYPE=1;

double REDUCTION_IN_TRANSGENIC_MALES_MATING_COMPETITIVENESS=1.;
double REDUCTION_IN_TRANSGENIC_MALES_MATING_COMPETITIVENESS_DOMINANCE=0.5;

int EU_TYPE=1;
double FITNESS_COST_CONSTRUCT_ALPHA=0;
double FITNESS_COST_CONSTRUCT_BETA=0;
double FITNESS_COST_CONSTRUCT_GAMMA=0;
double FITNESS_COST_CONSTRUCT_DELTA=0;
double FITNESS_COST_DOMINANCE=0.5;

int MD_TYPE=1;
double FITNESS_COST_INSENSITIVE_TRANSGENE=0;
double FITNESS_COST_INSENSITIVE_NATURAL=0;
double FITNESS_COST_DRIVE_GENE=0;
double DRIVE_STRENGTH_SN=0.4;
double DRIVE_STRENGTH_IT=0;
double DRIVE_STRENGTH_IN=0;
double DRIVE_STRENGTH_MN=0;
double MD_FITNESS_COST_DOMINANCE=0.5;

int MEDEA_UNITS=0;
int MEDEA_CROSS_RESCUE=0;
double MEDEA_MATERNAL_LETHALITY=1.0;

double MEDEA_MATERNAL_FECUNDITY_LOSS=0.;
double MEDEA_MATERNAL_FECUNDITY_LOSS_DOMINANCE=0.;
double MEDEA_FITNESS_COST_PER_CONSTRUCT=0. ;
double MEDEA_FITNESS_COST_DOMINANCE=0.5 ;
int MEDEA_FEMALE_SPECIFIC_FITNESS_COST=0;

int NUMBER_OF_INCOMPATIBLE_WOLBACHIA = 0;
double WOLBACHIA_INFECTED_FEMALE_FECUNDITY_LOSS = 0.2;
double WOLBACHIA_LEVEL_OF_INCOMPATIBILITY = 1.;
double WOLBACHIA_MATERNAL_TRANSMISSION = 1.;
double WOLBACHIA_SURVIVAL_REDUCTION_FEMALE_ONSET_AGE = 20;
double WOLBACHIA_SURVIVAL_REDUCTION_FEMALE_FACTOR = 1.0;
double WOLBACHIA_SURVIVAL_REDUCTION_MALE_ONSET_AGE = 20;
double WOLBACHIA_SURVIVAL_REDUCTION_MALE_FACTOR = 1.0;
int WOLBACHIA_EGG_SURVIVAL_REDUCTION_ONSET_AGE = 14;
double WOLBACHIA_EGG_SURVIVAL_REDUCTION_FACTOR = 1.0;

int IS_RESCUE=0;
int NUMBER_OF_ADDITIONAL_LOCI = 1;
int NUMBER_OF_FEMALE_KILLING_LOCI=1;
double FEMALE_KILLING_EFFICIENCY=1.0;
int FKR_IS_EMBRYO_KILLING=true;
double KILLING_ALLELE_HOMOZYGOUS_FITNESS_COST=0.0;
double KILLING_ALLELE_FITNESS_COST_DOMINANCE=0.5;
double RESCUE_ALLELE_HOMOZYGOUS_FITNESS_COST=0.0;
double RESCUE_ALLELE_FITNESS_COST_DOMINANCE=0.5;
double TRANSGENE_ALLELE_HOMOZYGOUS_FITNESS_COST=0.0;
double TRANSGENE_ALLELE_FITNESS_COST_DOMINANCE=0.5;

double MALE_KILLING_EFFICIENCY=1.0;
int NUMBER_OF_MALE_KILLING_LOCI=1;



double SELECTIVE_FITNESS_COST=0.;
double SELECTIVE_FITNESS_COST_DOMINANCE=0.5;

double OVITRAP_FEMALE_KILLING_EFFICIENCY=1.0;

bool SAD_INTRODUCTION=false;
int SAD_INTRODUCTION_DATE=365;
int SAD_INTRODUCTION_REGION=0;
int SAD_INTRODUCTION_X_MIN=0;
int SAD_INTRODUCTION_X_MAX=0;
int SAD_INTRODUCTION_Y_MIN=0;
int SAD_INTRODUCTION_Y_MAX=0;
double SAD_INTRODUCTION_FREQUENCY=0.0;
int SAD_INTRODUCTION_FEMALE_GENOTYPE=0;


bool OVIPOSIT_EGGS_INDEPENDENTLY = 0;
double PROBABILITY_CLUTCH_PARTITIONED = 0.85;
int MAXIMUM_NUMBER_OF_EGG_PARTITIONS = 4;

double PROPORTION_IN_PARTITION_0 = 0.45;
double PROPORTION_IN_PARTITION_1 = 0.2;
double PROPORTION_IN_PARTITION_2 = 0.2;
double PROPORTION_IN_PARTITION_3 = 0.15;
double PROPORTION_IN_PARTITION_4 = 0;
double PROPORTION_IN_PARTITION_5 = 0;
double PROPORTION_IN_PARTITION_6 = 0;
double PROPORTION_IN_PARTITION_7 = 0;
double PROPORTION_IN_PARTITION_8 = 0;
double PROPORTION_IN_PARTITION_9 = 0;

double LARVAL_EFFECT_ON_OVIPOSITION_PROBABILITY = 1;

double R=1.987;

double RO25_EMBRYONATION=0.01066;
double DHA_EMBRYONATION=10798.18;
double DHH_EMBRYONATION=100000;
double THALF_EMBRYONATION=14184.5;

double RO25_LARVAL_DEVELOPMENT=0.00873;
double DHA_LARVAL_DEVELOPMENT=26018.51;
double DHH_LARVAL_DEVELOPMENT=55990.75;
double THALF_LARVAL_DEVELOPMENT=304.58;

double RO25_PUPAL_DEVELOPMENT=0.0161;
double DHA_PUPAL_DEVELOPMENT=14931.94;
double DHH_PUPAL_DEVELOPMENT=-472379;
double THALF_PUPAL_DEVELOPMENT=148.45;

double RO25_GONOTROPHIC_CYCLE=0.00898;
double DHA_GONOTROPHIC_CYCLE=15725.23;
double DHH_GONOTROPHIC_CYCLE=1756481;
double THALF_GONOTROPHIC_CYCLE=447.17;

double PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_EMBRYONATION=0.95;
double SKEETER_BUSTER_PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_PUPATION=0.95;
double CIMSIM_PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_PUPATION=0.95;
double PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_EMERGENCE=0.95;
double PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_FIRST_GONOTROPHIC_CYCLE=1;
double PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_LATER_GONOTROPHIC_CYCLES=0.58;

double SKEETER_BUSTER_PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_FIRST=0.89;
double SKEETER_BUSTER_PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_LAST=1.17;
double SKEETER_BUSTER_PHYSIOLOGICAL_DEVELOPMENT_THRESHOLD_SHAPE=2.0126;

double NOMINAL_DAILY_SURVIVAL_EGGS=0.99;
double NOMINAL_DAILY_SURVIVAL_FEMALE_LARVAE=0.99;
double NOMINAL_DAILY_SURVIVAL_MALE_LARVAE=0.99;
double NOMINAL_DAILY_SURVIVAL_FEMALE_PUPAE=0.99;
double NOMINAL_DAILY_SURVIVAL_MALE_PUPAE=0.99;
double CIMSIM_NOMINAL_DAILY_SURVIVAL_FEMALE_ADULTS=0.91;
double CIMSIM_NOMINAL_DAILY_SURVIVAL_MALE_ADULTS=0.91;
double SKEETER_BUSTER_NOMINAL_DAILY_SURVIVAL_FEMALE_ADULTS=0.89;
double SKEETER_BUSTER_NOMINAL_DAILY_SURVIVAL_MALE_ADULTS=0.77;

int FEMALE_AGE_DEPENDENT_SURVIVAL=0 ;
int FEMALE_MAXIMUM_AGE_1 = 20 ;
int FEMALE_START_SENESCENCE_2 = 10 ;
int FEMALE_MAXIMUM_AGE_2 = 20 ;

int MALE_AGE_DEPENDENT_SURVIVAL=0 ;
int MALE_MAXIMUM_AGE_1 = 20 ;
int MALE_START_SENESCENCE_2 = 10 ;
int MALE_MAXIMUM_AGE_2 = 20 ;

double EGG_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double EGG_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=-14;
double EGG_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=-6;
double EGG_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=30;
double EGG_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double EGG_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=47;

double FEMALE_LARVAE_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double FEMALE_LARVAE_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=5;
double FEMALE_LARVAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=10;
double FEMALE_LARVAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=39;
double FEMALE_LARVAE_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double FEMALE_LARVAE_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=44;

double MALE_LARVAE_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double MALE_LARVAE_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=5;
double MALE_LARVAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=10;
double MALE_LARVAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=39;
double MALE_LARVAE_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double MALE_LARVAE_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=44;

double FEMALE_PUPAE_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double FEMALE_PUPAE_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=5;
double FEMALE_PUPAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=10;
double FEMALE_PUPAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=39;
double FEMALE_PUPAE_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double FEMALE_PUPAE_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=44;

double MALE_PUPAE_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double MALE_PUPAE_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=5;
double MALE_PUPAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=10;
double MALE_PUPAE_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=39;
double MALE_PUPAE_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double MALE_PUPAE_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=44;

double FEMALE_ADULT_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double FEMALE_ADULT_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=0;
double FEMALE_ADULT_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=4;
double FEMALE_ADULT_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=40;
double FEMALE_ADULT_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double FEMALE_ADULT_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=50;

double MALE_ADULT_DAILY_SURVIVAL_LOW_TEMPERATURE=0.05;
double MALE_ADULT_DAILY_SURVIVAL_LOW_TEMPERATURE_LIMIT=0;
double MALE_ADULT_DAILY_SURVIVAL_NORMAL_TEMPERATURE_LOWER_LIMIT=4;
double MALE_ADULT_DAILY_SURVIVAL_NORMAL_TEMPERATURE_UPPER_LIMIT=40;
double MALE_ADULT_DAILY_SURVIVAL_HIGH_TEMPERATURE=0.05;
double MALE_ADULT_DAILY_SURVIVAL_HIGH_TEMPERATURE_LIMIT=50;

double EGG_DAILY_SURVIVAL_WET_CONTAINER=1;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_SUNEXPOSURE_LIMIT=0.85;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_LOW_SUNEXPOSURE_LOW_SATURATIONDEFICIT_LIMIT=10;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_LOW_SUNEXPOSURE_HIGH_SATURATIONDEFICIT_LIMIT=40;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_LOW_SUNEXPOSURE_LOW_SATURATIONDEFICIT=0.99;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_LOW_SUNEXPOSURE_HIGH_SATURATIONDEFICIT=0.95;
double EGG_DAILY_SURVIVAL_DRY_CONTAINER_HIGH_SUNEXPOSURE=0.95;

double FEMALE_LARVAE_DAILY_SURVIVAL_DRY_CONTAINER=0.05;

double MALE_LARVAE_DAILY_SURVIVAL_DRY_CONTAINER=0.05;

double FEMALE_ADULT_DAILY_SURVIVAL_LOW_SATURATIONDEFICIT_LIMIT=10;
double FEMALE_ADULT_DAILY_SURVIVAL_HIGH_SATURATIONDEFICIT_LIMIT=30;
double FEMALE_ADULT_DAILY_SURVIVAL_LOW_SATURATIONDEFICIT=1;
double FEMALE_ADULT_DAILY_SURVIVAL_HIGH_SATURATIONDEFICIT=0.95;

double MALE_ADULT_DAILY_SURVIVAL_LOW_SATURATIONDEFICIT_LIMIT=10;
double MALE_ADULT_DAILY_SURVIVAL_HIGH_SATURATIONDEFICIT_LIMIT=30;
double MALE_ADULT_DAILY_SURVIVAL_LOW_SATURATIONDEFICIT=1;
double MALE_ADULT_DAILY_SURVIVAL_HIGH_SATURATIONDEFICIT=0.95;

double EGG_DAILY_SURVIVAL_TOPREDATION_LOW_TEMPERATURE_LIMIT=20;
double EGG_DAILY_SURVIVAL_TOPREDATION_HIGH_TEMPERATURE_LIMIT=30;
double EGG_DAILY_SURVIVAL_TOPREDATION_LOW_TEMPERATURE=1;
double EGG_DAILY_SURVIVAL_TOPREDATION_HIGH_TEMPERATURE=0.8;

double MINIMUM_TEMPERATURE_FOR_EGGHATCH=18;
double RATIO_OF_EGGS_HATCHING_WITHOUT_FLOODING=0.197;
double DAILY_RATIO_OF_EMBRYONATED_EGGS_THAT_HATCH_IF_SUBMERGED=0.596;
double EGGS_SEX_PERCENTAGE_FEMALE=0.5;

double SKEETER_BUSTER_FEMALE_LARVAE_WEIGHT_AT_HATCH=0.001;
double CIMSIM_FEMALE_LARVAE_WEIGHT_AT_HATCH=0.0034;
double FEMALE_LARVAE_DAILY_SURVIVAL_FASTING_WITH_LIPID_RESERVE=0.95;
double FEMALE_LARVAE_DAILY_SURVIVAL_FASTING_WITHOUT_LIPID_RESERVE=0.5;
double FEMALE_LARVAE_SMALLEST_WEIGHT_FOR_SURVIVAL=0.0009;
double SKEETER_BUSTER_FEMALE_LARVAE_MAXIMAL_PHYSIOLOGICAL_DEVELOPMENTAL_TIME_FOR_SURVIVAL=8;
double CIMSIM_FEMALE_LARVAE_MAXIMAL_PHYSIOLOGICAL_DEVELOPMENTAL_TIME_FOR_SURVIVAL=8;
double FEMALE_LARVAE_CONVERSION_RATE_OF_CONSUMED_FOOD_TO_BIOMASS=0.3;
double FEMALE_LARVAE_INCREMENT_OF_INCREASE_OF_RATE_OF_FOOD_EXPLOITATION=0.8;
double FEMALE_LARVAE_ASYMPTOTIC_RATE_OF_FOOD_EXPLOITATION_AT_HIGH_FOOD_DENSITIES=20;
double FEMALE_LARVAE_RATE_OF_METABOLIC_WEIGHT_LOSS_AS_A_FUNCTION_OF_DRY_WEIGHT_OF_LARVAE=0.016;
double FEMALE_LARVAE_EXPONENT_OF_METABOLIC_REQUIREMENTS_OF_LARVAE_AS_A_FUNCTION_OF_DRY_WEIGHT_OF_LARVAE=0.667;
double FEMALE_LARVAE_CHRONOLOGICAL_BASIS_AT_26C=0.001;
double FEMALE_LARVAE_MINIMUM_LIPID_RATIO_OF_LIVING_LARVAE=0.15;
double FEMALE_LARVAE_CONVERSION_OF_DRY_BODY_WEIGHT_TO_LIPID_RESERVE_PARAMETER_ONE=0.059;
double FEMALE_LARVAE_CONVERSION_OF_DRY_BODY_WEIGHT_TO_LIPID_RESERVE_PARAMETER_TWO=6.9;
double FEMALE_LARVAE_CONVERSION_RATE_OF_CADAVERS_TO_FOOD=0.4;
double FEMALE_LARVAE_SURVIVAL_AT_PUPATION_DUE_TO_BIRTH_DEFECTS=0.95;

int LARVAE_NUMBER_OF_EULER_STEPS=8;


//SKEETER BUSTER
double SKEETER_BUSTER_FEMALE_LARVAE_ABSOLUTE_MINIMUM_WEIGHT_FOR_PUPATION=0.1;
double SKEETER_BUSTER_FEMALE_LARVAE_SLOPE_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=-0.0389;
double SKEETER_BUSTER_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=1.79935;
double SKEETER_BUSTER_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_25=1.541121272542;
double SKEETER_BUSTER_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_50=1.79935;
double SKEETER_BUSTER_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_75=2.32698039000174;
double SKEETER_BUSTER_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_100=2.854526078000348;
double SKEETER_BUSTER_FEMALE_LARVAE_PHYSIOLOGICAL_DEVELOPMENTAL_PERCENT_FOR_WMIN=0.95;



//CIMSIM
double CIMSIM_FEMALE_LARVAE_ABSOLUTE_MINIMUM_WEIGHT_FOR_PUPATION=0.1;
double CIMSIM_FEMALE_LARVAE_SLOPE_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=-0.0389;
double CIMSIM_FEMALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=2.11;
double CIMSIM_FEMALE_LARVAE_PHYSIOLOGICAL_DEVELOPMENTAL_PERCENT_FOR_WMIN=0.95;


double SKEETER_BUSTER_MALE_LARVAE_WEIGHT_AT_HATCH=0.001;
double CIMSIM_MALE_LARVAE_WEIGHT_AT_HATCH=0.0034;
double MALE_LARVAE_DAILY_SURVIVAL_FASTING_WITH_LIPID_RESERVE=0.95;
double MALE_LARVAE_DAILY_SURVIVAL_FASTING_WITHOUT_LIPID_RESERVE=0.5;
double MALE_LARVAE_SMALLEST_WEIGHT_FOR_SURVIVAL=0.0009;
double SKEETER_BUSTER_MALE_LARVAE_MAXIMAL_PHYSIOLOGICAL_DEVELOPMENTAL_TIME_FOR_SURVIVAL=8;
double CIMSIM_MALE_LARVAE_MAXIMAL_PHYSIOLOGICAL_DEVELOPMENTAL_TIME_FOR_SURVIVAL=8;
double MALE_LARVAE_CONVERSION_RATE_OF_CONSUMED_FOOD_TO_BIOMASS=0.3;
double MALE_LARVAE_INCREMENT_OF_INCREASE_OF_RATE_OF_FOOD_EXPLOITATION=0.8;
double MALE_LARVAE_ASYMPTOTIC_RATE_OF_FOOD_EXPLOITATION_AT_HIGH_FOOD_DENSITIES=20;
double MALE_LARVAE_RATE_OF_METABOLIC_WEIGHT_LOSS_AS_A_FUNCTION_OF_DRY_WEIGHT_OF_LARVAE=0.016;
double MALE_LARVAE_EXPONENT_OF_METABOLIC_REQUIREMENTS_OF_LARVAE_AS_A_FUNCTION_OF_DRY_WEIGHT_OF_LARVAE=0.667;
double MALE_LARVAE_CHRONOLOGICAL_BASIS_AT_26C=0.001;
double MALE_LARVAE_MINIMUM_LIPID_RATIO_OF_LIVING_LARVAE=0.15;
double MALE_LARVAE_CONVERSION_OF_DRY_BODY_WEIGHT_TO_LIPID_RESERVE_PARAMETER_ONE=0.059;
double MALE_LARVAE_CONVERSION_OF_DRY_BODY_WEIGHT_TO_LIPID_RESERVE_PARAMETER_TWO=6.9;
double MALE_LARVAE_SURVIVAL_AT_PUPATION_DUE_TO_BIRTH_DEFECTS=0.95;


//SKEETER BUSTER
double SKEETER_BUSTER_MALE_LARVAE_ABSOLUTE_MINIMUM_WEIGHT_FOR_PUPATION=0.1;
double SKEETER_BUSTER_MALE_LARVAE_SLOPE_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=-0.0389;
double SKEETER_BUSTER_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=1.44935;
double SKEETER_BUSTER_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_25=1.227508848485034003875;
double SKEETER_BUSTER_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_50=1.44935;
double SKEETER_BUSTER_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_75=1.9664689009965085625;
double SKEETER_BUSTER_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T_100=2.483587801993017125;
double SKEETER_BUSTER_MALE_LARVAE_PHYSIOLOGICAL_DEVELOPMENTAL_PERCENT_FOR_WMIN=0.95;

//CIMSIM
double CIMSIM_MALE_LARVAE_ABSOLUTE_MINIMUM_WEIGHT_FOR_PUPATION=0.1;
double CIMSIM_MALE_LARVAE_SLOPE_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=-0.0389;
double CIMSIM_MALE_LARVAE_INTERCEPT_OF_MINIMAL_LARVAL_WEIGHT_FOR_PUPATION_AS_FUNCTION_OF_T=2.11;
double CIMSIM_MALE_LARVAE_PHYSIOLOGICAL_DEVELOPMENTAL_PERCENT_FOR_WMIN=0.95;


double FEMALE_PUPAE_SURVIVAL_AT_EMERGENCE=0.83;
double FEMALE_ADULT_CONVERSION_FACTOR_OF_DRY_WEIGHT_OF_LARVAE_TO_WET_WEIGHT_OF_ADULT=1.655;
double FEMALE_ADULT_DAILY_FECUNDITY_FACTOR_FOR_WET_WEIGHT=45.9;
double SKEETER_BUSTER_FECUNDITY_DROP_BY_AGE=-0.4366743082605775688381464;
double SKEETER_BUSTER_FECUNDITY_RATIO_STANDARD_DEVIATION_MEAN=0.37519462718322044613246790767955;
double FEMALE_ADULT_MINIMUM_TEMPERATURE_FOR_OVIPOSITION=18;


double MALE_PUPAE_SURVIVAL_AT_EMERGENCE=0.83;

double NULLIPAROUS_FEMALE_ADULT_DISPERSAL=0.3;
double PAROUS_FEMALE_ADULT_DISPERSAL=0.3;
double MALE_ADULT_DISPERSAL=0.3;
double NULLIPAROUS_FEMALE_ADULT_DISPERSAL_FROM_EMPTY_HOUSE=0.8;
double PAROUS_FEMALE_ADULT_DISPERSAL_FROM_EMPTY_HOUSE=0.8;
double MALE_ADULT_DISPERSAL_WHEN_NO_FEMALE=0.8;
int DISPERSAL_DIRECTION_BIAS=1;
int MAX_NUMBER_OF_DISPERSAL_STEPS=1;

double NULLIPAROUS_FEMALE_ADULT_LONG_RANGE_DISPERSAL=0.;
double PAROUS_FEMALE_ADULT_LONG_RANGE_DISPERSAL=0.;
double MALE_ADULT_LONG_RANGE_DISPERSAL=0.;
int LR_DISPERSAL_MAX_DISTANCE=10;

double CONTAINER_MOVEMENT_PROBABILITY=0 ;
double PROBABILITY_OF_EMPTYING_MANUALLY_FILLED_CONTAINERS=0.5;
double OVIPOSITION_REDUCTION_IN_COVERED_CONTAINERS=0.1 ;
double FILLING_FREQUENCY_TYPE_3_CONTAINERS=7;

double FEMALE_DAILY_RECAPTURE_RATE=0.0305;
double MALE_DAILY_RECAPTURE_RATE=0.0465;

double DAILY_REMATING_PROBABILITY_PAROUS_FEMALES=0.0;

//degree-day parameters
double MINIMUM_DEVELOPMENTAL_TEMPERATURE=13.4;
double DEGREE_HOURS_TO_BE_REACHED=1509.090914578;

//House setup parameters
int SCENARIO = 5;
int NUMBER_OF_COLUMNS=1;
int NUMBER_OF_ROWS=1;
int NUMBER_OF_HOUSES=1;

string WEATHER_YEAR_ONE="iquitos99.dly";
string WEATHER_YEAR_TWO="iquitos00.dly";
string WEATHER_YEAR_THREE="iquitos01.dly";
string WEATHER_YEAR_FOUR="iquitos02.dly";
string WEATHER_YEAR_FIVE="iquitos03.dly";
string WEATHER_YEAR_SIX="iquitos04.dly";
string WEATHER_YEAR_SEVEN="iquitos05.dly";
string WEATHER_YEAR_EIGHT="iquitos06.dly";

// location specific tweaks

bool GORDONVALE_REMOVE_173_195=false;
bool GORDONVALE_GOLF_COURSE=false;
bool IS_IQUITOS=false;


